name: Node.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Build Script
        run: npm run build

      - name: Run Tests (Optional)
        run: echo "No tests defined"  # Replace with actual tests if needed

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-files
          path: dist/
